### ISSUE TITLE
Does not fire "0" if released

### ISSUE THREAD

**Issue by neilyoung** [pavelzaichyk/flutter_joystick#3]

**Comment by philipwestling** [comment]
Did you manage to solve the problem?

**Comment by neilyoung** [comment]
Don’t remember 😀

**Comment by PhilipWestling** [comment]
Ah, shame. Thanks anyway!

Den ons 21 dec. 2022 kl 16:32 skrev neilyoung ***@***.***>:

**Comment by philipwestling** [comment]
Ah, shame. Thank's anyway!

**Comment by neilyoung** [comment]
Now, that you say it... I recall I patched the widget. Something with the behaviour ad dragEnd https://github.com/pavelzaichyk/flutter_joystick/blob/9a37389129ba6184fe8d790851048365f9b904d5/lib/src/joystick.dart#L114

Since I have the project no longer on my disk I can't be more precise. Would have to restore it from backup. Possible after Christmas only :)

Maybe this helps. Sorry, I'm getting older, things are disappearing  from mind very quickly

**Comment by philipwestling** [comment]
No worries, I'll have a look 👍

**Comment by pavelzaichyk** [comment]
Check `flutter_joystick: 0.0.3` version
Now the listener gets zeros when the control is released.

**Comment by neilyoung** [comment]
Yes. Basically my solution was similar. Thanks for fixing it officially
